### ISSUE TITLE
Listing - when filtered the "load more" button isn't working

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#82]
https://swissgames.garden/?platforms[]=ios&platforms[]=windows
![Screenshot 2022-03-14 at 13 13 53](https://user-images.githubusercontent.com/27284929/158170096-161f0fdc-2216-4b4e-9167-45950ba1578b.png)

**Comment by tonifisler** [comment]
Due to some server issues. I really don't know how to fix this.

**Comment by WengerK** [comment]
there is no more server issue, the problem is reproducible on local docker environment by:

1. Go to the index (server-side)
2. See the pager works (as it has been built server-side)
3. Click on any game teaser and reach the game detail page (rehydrated)
4. click on the logo header to visit the homepage again (rehydrate)
5. See the pager is broken

I supposed it's due to rehydrataion that does not update a variable leading the pager to empty

**Comment by WengerK** [comment]
fixed
